### ISSUE TITLE
Possibility to set "strategies" statically

### ISSUE THREAD

**Issue by kriwar** [m00ndark/net-mock#16]
Would be nice to be able to set...
* MockBehavior
* UndefinedQueryParameterHandling
* UndefinedHeaderHandling
* possibly other "behavior" type configuration
...statically on ServiceMock level, with possibility, to "override" on RestMock level.

Also, consider more uniform naming and defaults of these settings!

**Comment by m00ndark** [comment]
Statically:
`ServiceMock.GlobalConfig.ActivationStrategy`
`ServiceMock.GlobalConfig.MockBehavior`
`ServiceMock.GlobalConfig.PrintReceivedRequestsOnTearDown`
`RestMock.GlobalConfig.DefaultResponseStatusCode`
`RestMock.GlobalConfig.UndefinedQueryParameterHandling`
`RestMock.GlobalConfig.UndefinedHeaderHandling`
`RestMock.GlobalConfig.MockBehavior`
`RestMock.GlobalConfig.InterpretBodyAsJson`

Per instance:
`serviceMock.ActivationStrategy`
`serviceMock.MockBehavior`
`serviceMock.PrintReceivedRequestsOnTearDown`
`restMock.DefaultResponseStatusCode`
`restMock.UndefinedQueryParameterHandling`
`restMock.UndefinedHeaderHandling`
`restMock.MockBehavior`
`restMock.InterpretBodyAsJson`

Order of precedence:
`RestMock` instance > `RestMock.GlobalConfig` > `ServiceMock` instance > `ServiceMock.GlobalConfig`
